---
grails:
    profile: web
    codegen:
        defaultPackage: demo
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    cors:
        enabled: true
        allowCredentials: true
        allowedOrigins:
            - http://localhost:8080
            - http://localhost:8081
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

server:
    port: 8090

aws:
    s3:
        enable: ${aws_s3_enable:true}
        region: ${aws_s3_region:cn-north-1}
        accessKey: ${aws_s3_accessKey:AKIAQ2LY5SYVRBN3C72J}
        secretKey: ${aws_s3_secretKey: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}
        bucketName: ${aws_s3_bucketName:cnn-s3-rg-sma-prd}
---
grails:
    plugin:
        databasemigration:
            updateOnStart: true
            updateOnStartFileNames: ['changelog.groovy']
kafkaServer:
    bootstrap:
        servers: localhost:9092
kafka:
    demo:
        topic: "demo"
        groupId: "demo_group"
        otherGroupId: "demo2_group"
        numConsumers: 5

chatgpt:
    api-key: ENC:pthOq8RvRWXWXkQALqInYH/3GHsV5zA7qI5bbraNSuQceBXCnPyZOBx0bIc6c74fCQhENdythZBtaFb3PU+Qpg==
redis:
    haMode: ${redis_haMode:standalone}
    enableSsl: ${redis_enableSsl:false}
    host: 127.0.0.1
    password:
    port: 6379
    poolConfig:
        maxIdle: 10
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dbCreate: none
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        initSQL: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
DmHub:
    appid: "cl014418b414873a4"
    secret: "ffcb95a1ff86d3cef7633faaf7c08079a455fd91"
